---
- name: "download rke2 agent"
  become: true
  shell: |
    echo "===========download rke2 agent============"
    curl -sfL https://get.rke2.io  | INSTALL_RKE2_VERSION={{RKE2_VERSION}} INSTALL_RKE2_TYPE="agent" sh -

    systemctl enable rke2-agent.service
  tags: 
      - rke2-agent-multi-master
      - rke2-cluster-multi


- name: "join  agent node"
  become: true
  shell: |
    mkdir -p /etc/rancher/rke2/
    
    echo "========RKE2_AGENT_MULTI_MASTER_URL : {{RKE2_AGENT_MULTI_MASTER_URL}} , token : {{RKE2_MASTER_SERVER_TOKEN}}"
    cat <<EOF > /etc/rancher/rke2/config.yaml
    server: {{RKE2_AGENT_MULTI_MASTER_URL}}
    token: {{RKE2_MASTER_SERVER_TOKEN}}
    EOF
  register: output
  tags: 
    - rke2-agent-multi-master
    - rke2-cluster-multi

- debug:
    var: output
  tags: 
    - rke2-agent-multi-master
    - rke2-cluster-multi

- name: " start rke2 agent "
  become: true
  shell: |
    echo "=======rke2-agent start============"
    systemctl start rke2-agent.service
  register: output
  tags: 
    - rke2-agent-multi-master
    - rke2-cluster-multi

- debug:
    var: output
  tags: 
    - rke2-agent-multi-master
    - rke2-cluster-multi


######### delete rke2 agent ##########
- name: "rke2-agent-multi-mater delete"
  become: true
  shell: |
    rke2-uninstall.sh
  tags: 
    - rke2-agent-multi-master-delete
    - rke2-cluster-multi-delete
  