---

    
######## argocd #########

- name: "[필수사항 체크] Ingress Controller 설치 여부 체크"
  ansible.builtin.shell: | 
    kubectl get pod -n {{GLB_INGRESS_NAMESPACE}} | grep {{ARGOCD_INGRESS_CLASS}} |wc -l
  register: output
  failed_when:  "output.stdout|float < 1"
  tags:
    - argocd

- name: argocd 설치
  shell: |
    kubectl create ns argocd
    kubectl -n argocd apply  -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    kubectl wait pod --timeout=-1s --for=condition=Ready -l '!job-name' -n argocd  > /dev/null
  
  register: output
  tags: 
    - argocd

- name: argo-rollouts 설치 
  shell: |
    kubectl create ns argo-rollouts
    kubectl apply -n argo-rollouts  -f https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml
    kubectl wait pod --timeout=-1s --for=condition=Ready -l '!job-name' -n  argo-rollouts  > /dev/null
  register: output
  tags:
    - argo-rollouts
    - argocd
  when: ARGO_ROLLOUTS_YN == 'Y' 


- name: argocd ingress 설치 
  kubernetes.core.k8s:
    state: present
    template: 
      - path: "argocd/argocd-ingress.yml.j2"
  register: output
  tags: 
    - argocd-ing
    - argocd
  when: ARGOCD_INGRESS_YN == 'Y' and ARGOCD_INGRESS_CLASS == 'nginx'

- debug:
    var: output
  tags: 
    - argocd-ing
    - argocd

- name: agrocd  change account password
  shell: |
    PASSWORD="$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d && echo )"
    argocd login --insecure {{ARGOCD_HOST}}  --username admin  --password $PASSWORD 
    argocd account update-password --current-password $PASSWORD  --new-password {{ARGOCD_NEW_PASSWORD}}
  register: output
  tags: 
    - arogocd-pwd
    - argocd
  when: ARGOCD_INGRESS_YN == 'Y'

- debug:
    var: output
  tags:
    - arogocd-pwd
    - argocd
  when: ARGOCD_INGRESS_YN == 'Y'


- name: application simple-api  deploy
  shell: |
    kubectl create ns api

    argocd app create simple-api \
    --repo https://github.com/io203/simple-gitOps.git  \
    --revision master \
    --path  simple-api/rolling \
    --dest-server https://kubernetes.default.svc \
    --dest-namespace api \
    --sync-policy automated \
    --sync-option CreateNamespace=true \
    --upsert

    argocd app sync simple-api
  tags: 
    - app-deploy

- name: application simple-fe deploy
  shell: |
    kubectl create ns fe
    argocd app create simple-fe \
    --repo https://github.com/io203/simple-gitOps.git  \
    --revision master \
    --path  simple-fe/rolling \
    --dest-server https://kubernetes.default.svc \
    --dest-namespace fe \
    --sync-policy automated \
    --sync-option CreateNamespace=true \
    --upsert

    argocd app sync simple-fe
  tags: 
    - app-deploy

- name: simple-fe ingress 설치 
  kubernetes.core.k8s:
    state: present
    template: 
      - path: "simple/simple-fe-ingress.yml.j2"
  register: output
  tags: 
    - simple-fe-ing
    - app-deploy

- debug:
    var: output
  tags:
    - simple-fe-ing
    - app-deploy








