---
- hosts: "all"  
  tasks:
    - name: "[pre] apt update"
      apt:
        update_cache: yes
      become: true
      tags: rke2-pre
    - name: "pip 설치"
      apt: 
        name: python3-pip   
      become: true  
      tags: rke2-pre

    - name: install ansible server module pre-requisites
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes 
          - "docker==6.1.3" # 이슈 (docker==7.0.0): https://github.com/docker/docker-py/issues/3194, https://github.com/geerlingguy/internet-pi/issues/567
          - docker-compose
      tags: rke2-pre

    - name: "[server] rke2 Prerequisites "
      become: true
      shell: |
        sudo swapoff -a
        apt-get update -y
        systemctl stop ufw && ufw disable && iptables -F   
      register: output
      tags: 
        - rke2-pre
      


- hosts: lb
  vars: 
  -  ROLES_PATH: ../roles
  roles:
    - role: "{{ROLES_PATH}}/k8s-cluster/role-lb-db-k8s"

- hosts: "masters"
  serial: 1
  vars: 
  -  ROLES_PATH: ../roles
  roles:
    - role: "{{ROLES_PATH}}/k8s-cluster/role-k8s-master"

- hosts: "workers"
  serial: 1
  vars:
  - ROLES_PATH: ../roles
  roles:
    - role: "{{ROLES_PATH}}/k8s-cluster/role-k8s-worker"




